import {MEDIA_CHANNEL} from '../../cc-components/src/components/task/task.types';

export const mockTaskData = {
  active: {
    telephony: {
      ani: '1234567890',
      customerName: 'John Doe',
      virtualTeamName: 'Support Team',
      ronaTimeout: null,
      taskState: 'active',
      startTimeStamp: 1641234567890,
      isIncomingTask: false,
      mediaType: MEDIA_CHANNEL.TELEPHONY,
      mediaChannel: MEDIA_CHANNEL.TELEPHONY,
      isTelephony: true,
      isSocial: false,
      acceptText: undefined,
      declineText: undefined,
      title: '1234567890',
      disableAccept: false,
      displayState: 'active',
    },
    chat: {
      ani: 'chat-user-123',
      customerName: 'Chat Customer',
      virtualTeamName: 'Chat Team',
      ronaTimeout: null,
      taskState: 'active',
      startTimeStamp: 1641234567890,
      isIncomingTask: false,
      mediaType: MEDIA_CHANNEL.CHAT,
      mediaChannel: MEDIA_CHANNEL.CHAT,
      isTelephony: false,
      isSocial: false,
      acceptText: undefined,
      declineText: undefined,
      title: 'Chat Customer',
      disableAccept: false,
      displayState: 'active',
    },
    facebook: {
      ani: 'facebook-user-456',
      customerName: 'Facebook Customer',
      virtualTeamName: 'Social Team',
      ronaTimeout: null,
      taskState: 'active',
      startTimeStamp: 1641234567890,
      isIncomingTask: false,
      mediaType: MEDIA_CHANNEL.SOCIAL,
      mediaChannel: MEDIA_CHANNEL.FACEBOOK,
      isTelephony: false,
      isSocial: true,
      acceptText: undefined,
      declineText: undefined,
      title: 'Facebook Customer',
      disableAccept: false,
      displayState: 'active',
    },
  },
  incoming: {
    webrtcTelephony: {
      ani: '1234567890',
      customerName: 'WebRTC Customer',
      virtualTeamName: 'Support',
      ronaTimeout: 30,
      taskState: 'new',
      startTimeStamp: undefined,
      isIncomingTask: true,
      mediaType: MEDIA_CHANNEL.TELEPHONY,
      mediaChannel: MEDIA_CHANNEL.TELEPHONY,
      isTelephony: true,
      isSocial: false,
      acceptText: 'Accept',
      declineText: 'Decline',
      title: '1234567890',
      disableAccept: false,
      displayState: '',
    },
    extensionTelephony: {
      ani: '1234567890',
      customerName: 'Extension Customer',
      virtualTeamName: 'Support',
      ronaTimeout: 30,
      taskState: 'new',
      startTimeStamp: undefined,
      isIncomingTask: true,
      mediaType: MEDIA_CHANNEL.TELEPHONY,
      mediaChannel: MEDIA_CHANNEL.TELEPHONY,
      isTelephony: true,
      isSocial: false,
      acceptText: 'Ringing...',
      declineText: undefined,
      title: '1234567890',
      disableAccept: true,
      displayState: '',
    },
    chat: {
      ani: 'chat-user-123',
      customerName: 'Chat Customer',
      virtualTeamName: 'Chat Support',
      ronaTimeout: 30,
      taskState: 'new',
      startTimeStamp: undefined,
      isIncomingTask: true,
      mediaType: MEDIA_CHANNEL.CHAT,
      mediaChannel: MEDIA_CHANNEL.CHAT,
      isTelephony: false,
      isSocial: false,
      acceptText: 'Accept',
      declineText: undefined,
      title: 'Chat Customer',
      disableAccept: false,
      displayState: '',
    },
  },
  action: {
    telephony: {
      ani: '1111111111',
      customerName: 'Action Customer',
      virtualTeamName: 'Action Team',
      ronaTimeout: 30,
      taskState: 'new',
      startTimeStamp: undefined,
      isIncomingTask: true,
      mediaType: MEDIA_CHANNEL.TELEPHONY,
      mediaChannel: MEDIA_CHANNEL.TELEPHONY,
      isTelephony: true,
      isSocial: false,
      acceptText: 'Accept',
      declineText: 'Decline',
      title: '1111111111',
      disableAccept: false,
      displayState: '',
    },
    activeTask: {
      ani: '1111111111',
      customerName: 'Active Customer',
      virtualTeamName: 'Active Team',
      ronaTimeout: null,
      taskState: 'active',
      startTimeStamp: 1641234567890,
      isIncomingTask: false,
      mediaType: MEDIA_CHANNEL.TELEPHONY,
      mediaChannel: MEDIA_CHANNEL.TELEPHONY,
      isTelephony: true,
      isSocial: false,
      acceptText: undefined,
      declineText: undefined,
      title: '1111111111',
      disableAccept: false,
      displayState: 'active',
    },
  },
  selection: {
    selectedTelephony: {
      ani: '1111111111',
      customerName: 'Selected Customer',
      virtualTeamName: 'Selected Team',
      ronaTimeout: 30,
      taskState: 'new',
      startTimeStamp: undefined,
      isIncomingTask: true,
      mediaType: MEDIA_CHANNEL.TELEPHONY,
      mediaChannel: MEDIA_CHANNEL.TELEPHONY,
      isTelephony: true,
      isSocial: false,
      acceptText: 'Accept',
      declineText: 'Decline',
      title: '1111111111',
      disableAccept: false,
      displayState: '',
    },
    unselectedChat: {
      ani: 'chat-user-456',
      customerName: 'Unselected Chat Customer',
      virtualTeamName: 'Chat Support Team',
      ronaTimeout: null,
      taskState: 'active',
      startTimeStamp: 1641234567890,
      isIncomingTask: false,
      mediaType: MEDIA_CHANNEL.CHAT,
      mediaChannel: MEDIA_CHANNEL.CHAT,
      isTelephony: false,
      isSocial: false,
      acceptText: undefined,
      declineText: undefined,
      title: 'Unselected Chat Customer',
      disableAccept: false,
      displayState: 'active',
    },
  },
};
