yarnPath: .yarn/releases/yarn-4.5.1.cjs

nodeLinker: node-modules

npmScopes:
  webex-engage:
    npmRegistryServer: 'https://engci-maven-master.cisco.com/artifactory/api/npm/webex-release-npm/'
    npmAuthIdent: 'cnNhcmlrYTpjbVZtZEd0dU9qQXhPakUzTlRnMk1UQXpNVFk2WmtnMVMyOVlSV2RsYkVkRlFXZDFValZ0YW1wd1FVUk5jbXMz'
    npmAlwaysAuth: true
