yarnPath: .yarn/releases/yarn-4.5.1.cjs
checksumBehavior: update
nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"

# Used for new CC Widgets UI 
npmScopes:
  agentx:
    npmRegistryServer: "https://engci-maven.cisco.com/artifactory/api/npm/agentx-npm/"
  uuip:
    npmRegistryServer: "https://engci-maven.cisco.com/artifactory/api/npm/unified-ui-platform-npm/"
  momentum-ui-private:
    npmRegistryServer: "https://engci-maven.cisco.com/artifactory/api/npm/momentum-ui-npm/"
  wxcc-desktop:
    npmRegistryServer: "https://engci-maven.cisco.com/artifactory/api/npm/wxcc-desktop-npm/"
  webex:
    npmRegistryServer: "https://engci-maven.cisco.com/artifactory/api/npm/webex-npm-group/"