yarnPath: .yarn/releases/yarn-4.5.1.cjs
checksumBehavior: update
nodeLinker: node-modules

npmScopes:
  webex:
    npmRegistryServer: 'https://engci-maven-master.cisco.com/artifactory/api/npm/webex-release-npm/'
    npmAuthToken: '<YOUR_AUTH_TOKEN_HERE>'
    npmAlwaysAuth: true
