yarnPath: .yarn/releases/yarn-4.5.1.cjs
checksumBehavior: update
nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"

# Used for new CC Widgets Station Login UI.
npmScopes:
  uuip:
    npmRegistryServer: "https://engci-maven.cisco.com/artifactory/api/npm/unified-ui-platform-npm/"
  momentum-ui-private:
    npmRegistryServer: "https://engci-maven.cisco.com/artifactory/api/npm/momentum-ui-npm/"