import {defineConfig, devices} from '@playwright/test';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({path: path.resolve(__dirname, '.env')});

const dummyAudioPath = path.resolve(__dirname, './playwright/wav/dummyAudio.wav');

export default defineConfig({
  testDir: './playwright',
  timeout: 180000,
  webServer: {
    command: 'yarn workspace samples-cc-react-app serve',
    url: 'http://localhost:3000',
    reuseExistingServer: !process.env.CI,
    stdout: 'ignore',
    stderr: 'pipe',
  },
  retries: 0,
  fullyParallel: true,
  workers: 5,
  reporter: 'html',
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'retain-on-failure',
  },
  projects: [
    {
      name: 'OAuth: Get Access Token',
      testMatch: /global\.setup\.ts/,
    },
    {
      name: 'SET_1',
      dependencies: ['OAuth: Get Access Token'],
      fullyParallel: false,
      retries: 1,
      testMatch: ['**/set1-tests.spec.ts'],
      use: {
        ...devices['Desktop Chrome'],
        channel: 'chrome',
        storageState: undefined,
        launchOptions: {
          args: [
            `--disable-site-isolation-trials`,
            `--disable-web-security`,
            `--no-sandbox`,
            `--disable-features=WebRtcHideLocalIpsWithMdns`,
            `--allow-file-access-from-files`,
            `--use-fake-ui-for-media-stream`,
            `--use-fake-device-for-media-stream`,
            `--use-file-for-fake-audio-capture=${dummyAudioPath}`,
            `--remote-debugging-port=9221`,
            `--disable-extensions`,
            `--disable-plugins`,
            `--window-position=0,0`,
            `--window-size=1280,720`,
          ],
        },
      },
    },
    {
      name: 'SET_2',
      fullyParallel: false,
      retries: 1,
      dependencies: ['OAuth: Get Access Token'],
      testMatch: ['**/set2-tests.spec.ts'],
      use: {
        ...devices['Desktop Chrome'],
        channel: 'chrome',
        storageState: undefined,
        launchOptions: {
          args: [
            `--disable-site-isolation-trials`,
            `--disable-web-security`,
            `--no-sandbox`,
            `--disable-features=WebRtcHideLocalIpsWithMdns`,
            `--allow-file-access-from-files`,
            `--use-fake-ui-for-media-stream`,
            `--use-fake-device-for-media-stream`,
            `--use-file-for-fake-audio-capture=${dummyAudioPath}`,
            `--remote-debugging-port=9222`,
            `--disable-extensions`,
            `--disable-plugins`,
            `--window-position=1300,0`,
            `--window-size=1280,720`,
          ],
        },
      },
    },
    {
      name: 'SET_3',
      fullyParallel: false,
      retries: 1,
      dependencies: ['OAuth: Get Access Token'],
      testMatch: ['**/set3-tests.spec.ts'],
      use: {
        ...devices['Desktop Chrome'],
        channel: 'chrome',
        storageState: undefined,
        launchOptions: {
          args: [
            `--disable-site-isolation-trials`,
            `--disable-web-security`,
            `--no-sandbox`,
            `--disable-features=WebRtcHideLocalIpsWithMdns`,
            `--allow-file-access-from-files`,
            `--use-fake-ui-for-media-stream`,
            `--use-fake-device-for-media-stream`,
            `--use-file-for-fake-audio-capture=${dummyAudioPath}`,
            `--remote-debugging-port=9223`,
            `--disable-extensions`,
            `--disable-plugins`,
            `--window-position=2600,0`,
            `--window-size=1280,720`,
          ],
        },
      },
    },
    {
      name: 'SET_4',
      fullyParallel: false,
      retries: 1,
      dependencies: ['OAuth: Get Access Token'],
      testMatch: ['**/set4-tests.spec.ts'],
      use: {
        ...devices['Desktop Chrome'],
        channel: 'chrome',
        storageState: undefined,
        launchOptions: {
          args: [
            `--disable-site-isolation-trials`,
            `--disable-web-security`,
            `--no-sandbox`,
            `--disable-features=WebRtcHideLocalIpsWithMdns`,
            `--allow-file-access-from-files`,
            `--use-fake-ui-for-media-stream`,
            `--use-fake-device-for-media-stream`,
            `--use-file-for-fake-audio-capture=${dummyAudioPath}`,
            `--remote-debugging-port=9224`,
            `--disable-extensions`,
            `--disable-plugins`,
            `--window-position=3900,0`,
            `--window-size=1280,720`,
          ],
        },
      },
    },
    {
      name: 'SET_5',
      fullyParallel: false,
      retries: 1,
      dependencies: ['OAuth: Get Access Token'],
      testMatch: ['**/set5-tests.spec.ts'],
      use: {
        ...devices['Desktop Chrome'],
        channel: 'chrome',
        storageState: undefined,
        launchOptions: {
          args: [
            `--disable-site-isolation-trials`,
            `--disable-web-security`,
            `--no-sandbox`,
            `--disable-features=WebRtcHideLocalIpsWithMdns`,
            `--allow-file-access-from-files`,
            `--use-fake-ui-for-media-stream`,
            `--use-fake-device-for-media-stream`,
            `--use-file-for-fake-audio-capture=${dummyAudioPath}`,
            `--remote-debugging-port=9225`,
            `--disable-extensions`,
            `--disable-plugins`,
            `--window-position=5200,0`,
            `--window-size=1280,720`,
          ],
        },
      },
    },
  ],
});
