import {Page, expect, Locator} from '@playwright/test';
import {AWAIT_TIMEOUT, AI_ASSIST_SUGGESTION_TIMEOUT} from '../constants';

/**
 * Utility functions for exercising the AI Assistant widget (launcher, landing
 * page, Real-Time Assist chat, and adaptive-card feedback controls) in e2e
 * tests.
 *
 * The suggestion content itself is generated by a live backend AI pipeline
 * during the test call, so these helpers deliberately avoid asserting on
 * exact transcript/suggestion text and instead verify structure and state
 * transitions (panel open, spinner clears, chat entries appear, feedback
 * controls toggle).
 *
 * @packageDocumentation
 */

/**
 * Enables the AI Assistant widget via its sample-app checkbox.
 * Unlike most widgets, AI Assistant defaults to unchecked, so this must be
 * called explicitly before the widget will render.
 * @param page - The Playwright page object
 */
export async function enableAIAssistantWidget(page: Page): Promise<void> {
  const checkbox = page.getByTestId('samples:widget-aiAssistant');
  const isChecked = await checkbox.isChecked().catch(() => false);
  if (!isChecked) {
    await checkbox.check({timeout: AWAIT_TIMEOUT});
  }
}

/**
 * Opens the AI Assistant panel by clicking its launcher button.
 * No-ops if the panel is already open (launcher only renders when closed).
 * @param page - The Playwright page object
 */
export async function openAIAssistant(page: Page): Promise<void> {
  const launcher = page.getByTestId('ai-assistant:launcher');
  if (await launcher.isVisible().catch(() => false)) {
    await launcher.click({timeout: AWAIT_TIMEOUT});
  }
  await expect(page.getByTestId('ai-assistant:panel')).toBeVisible({timeout: AWAIT_TIMEOUT});
}

/**
 * Closes the AI Assistant panel via its header close button.
 * @param page - The Playwright page object
 */
export async function closeAIAssistant(page: Page): Promise<void> {
  const closeButton = page.getByTestId('ai-assistant:header-close');
  if (await closeButton.isVisible().catch(() => false)) {
    await closeButton.click({timeout: AWAIT_TIMEOUT});
  }
}

/**
 * Returns true while the landing page (feature disabled / no active
 * interaction) is shown instead of the Real-Time Assist chat.
 * @param page - The Playwright page object
 */
export async function isShowingLanding(page: Page): Promise<boolean> {
  return page
    .getByTestId('ai-assistant:landing')
    .isVisible()
    .catch(() => false);
}

/**
 * Clicks "Get Suggestions" and waits for the request to settle: either the
 * chat/context-form appears (success) or the inline error message appears
 * (failure). Does not throw on failure - callers assert the outcome.
 * @param page - The Playwright page object
 */
export async function requestRealTimeAssistSuggestions(page: Page): Promise<void> {
  const getSuggestionsButton = page.getByTestId('ai-assistant:get-suggestions');
  await expect(getSuggestionsButton).toBeVisible({timeout: AWAIT_TIMEOUT});
  await getSuggestionsButton.click({timeout: AWAIT_TIMEOUT});

  // The button is replaced by a spinner while the request is in flight;
  // wait for the request to settle one way or another.
  await Promise.race([
    page.getByTestId('ai-assistant:context-form').waitFor({state: 'visible', timeout: AI_ASSIST_SUGGESTION_TIMEOUT}),
    page.getByTestId('ai-assistant:error').waitFor({state: 'visible', timeout: AI_ASSIST_SUGGESTION_TIMEOUT}),
  ]).catch(() => {});
}

/**
 * Waits for at least one assistant suggestion (adaptive card or greeting) to
 * appear in the Real-Time Assist chat.
 * @param page - The Playwright page object
 * @returns Locator for the first assistant chat entry
 */
export async function waitForFirstSuggestion(page: Page): Promise<Locator> {
  const assistantEntry = page.getByTestId('ai-assistant:chat-assistant').first();
  await assistantEntry.waitFor({state: 'visible', timeout: AI_ASSIST_SUGGESTION_TIMEOUT});
  return assistantEntry;
}

/**
 * Clicks the like/dislike feedback control (identified by its accessible
 * name) on the first rendered suggestion card and returns its locator so the
 * caller can assert on the resulting `data-active` state.
 * @param page - The Playwright page object
 * @param kind - Which control to click
 */
export async function clickSuggestionFeedback(page: Page, kind: 'like' | 'dislike'): Promise<Locator> {
  const label = kind === 'like' ? 'Like suggestion' : 'Dislike suggestion';
  const control = page.getByLabel(label).first();
  await expect(control).toBeVisible({timeout: AWAIT_TIMEOUT});
  await control.click({timeout: AWAIT_TIMEOUT});
  return control;
}

/**
 * Clicks the copy control on the first rendered suggestion card.
 * @param page - The Playwright page object
 * @returns Locator for the copy control
 */
export async function clickSuggestionCopy(page: Page): Promise<Locator> {
  const control = page.getByLabel('Copy suggestion').first();
  await expect(control).toBeVisible({timeout: AWAIT_TIMEOUT});
  await control.click({timeout: AWAIT_TIMEOUT});
  return control;
}
