import {Page, Locator} from '@playwright/test';
import {TRANSCRIPT_ENTRY_TIMEOUT} from '../constants';

/**
 * Utility functions for exercising the Real-Time Transcript widget in e2e
 * tests.
 *
 * Transcript content is generated by a live speech-to-text pipeline from the
 * dummy audio played on the call, so these helpers verify that entries
 * eventually appear rather than asserting on exact transcribed text.
 *
 * @packageDocumentation
 */

/**
 * Waits for the Real-Time Transcript panel to be visible.
 * The panel only renders while `store.currentTask` exists (an active call).
 * @param page - The Playwright page object
 * @param timeout - Optional timeout override in ms
 */
export async function waitForRealTimeTranscriptPanel(page: Page, timeout: number = TRANSCRIPT_ENTRY_TIMEOUT) {
  const root = page.getByTestId('real-time-transcript:root');
  await root.waitFor({state: 'visible', timeout});
  return root;
}

/**
 * Waits for at least one transcript entry to appear in the live transcript
 * feed.
 * @param page - The Playwright page object
 * @returns Locator for the first transcript item
 */
export async function waitForFirstTranscriptEntry(page: Page): Promise<Locator> {
  const item = page.getByTestId('real-time-transcript:item').first();
  await item.waitFor({state: 'visible', timeout: TRANSCRIPT_ENTRY_TIMEOUT});
  return item;
}

/**
 * Returns the count of transcript entries currently rendered.
 * @param page - The Playwright page object
 */
export async function getTranscriptEntryCount(page: Page): Promise<number> {
  return page.getByTestId('real-time-transcript:item').count();
}
